#!/bin/sh

set -e

echo "*****Running build ******"
./gradlew clean build

echo "*****Running tests ******"
./gradlew clean test

echo "******Running Checkstyle Main"
./gradlew clean checkstyleMain

echo "*******Running Checkstyle Test"
.gradlew clean checkstyleTest